### ISSUE TITLE
namespacing .avatar 

### ISSUE THREAD

**Issue by kevohagan** [bengott/meteor-avatar#72] opened 2015-05-29 11:12 UTC
using this package with materializecss i get a namespacing problems with .avatar classes 

http://materializecss.com/collections.html#!

maybe the solution would be to namespace your classes mavatar or something.

what do you think?

**Comment by raiyankamal** [comment] 2015-06-16 00:11
I think this is an excellent suggestion. I may give it a try in near future. Or if somebody wants to work on this, please go ahead. In the mean time, we can discuss what might be the best name for this intended namespace. I can think of the following ones:

- mavatar. Suggested by @kevohagan. Pros: short. Cons: not very succinct.
- meteoravatar. Pros: succinct. Cons: long name.
- meteor_avatar. Pros: succinct and easily readable. Cons: long name.

**Comment by raiyankamal** [comment] 2015-06-23 01:42
Hi @kevohagan, I finally had the time to look in to it today. I realized we already have a feature to add custom CSS classes. For example, you can use the avatar template like this:
```{{> avatar user=this size='small' shape='circle' class="foo"}}```
Then in your stylesheet:
```.avatar.foo {
/* all foo specific styling can go here */
}```
This should be sufficient prevent collision in CSS. What do you think?

**Comment by SachaG** [comment] 2015-06-24 02:19
I think the problem is if you already have an `.avatar` class defined elsewhere, it'll still affect `.avatar.foo`. We could just add a `classPrefix` option? PRs welcome :)

**Comment by raiyankamal** [comment] 2015-06-27 15:56
Got it. I'll start working on it today. Hopefully a PR will come your way by the end of the day.

**Comment by raiyankamal** [comment] 2015-07-04 11:35
A PR is sent @SachaG, have a look when you have the time

**Comment by raiyankamal** [comment] 2015-07-08 13:25
@kevohagan, the current version allows adding custom prefix to CSS classes. Please give it a try and consider closing this issue if you're satisfied. Cheers.

**Closed** 2016-09-19 21:28 UTC
